name: appcache
version: 0.1.2
author: João Furtado <jrofurtado@gmail.com>
description: A transformer to generate an appcache file
homepage: https://github.com/jrofurtado/dart-appcache
dependencies:
  barback: '>=0.15.2+2 <0.16.0'
  code_transformers: '>=0.2.3+2 <0.5.0'
  html5lib: any
transformers:
- appcache
